### ISSUE TITLE
Failed compilation in centos 7

### ISSUE THREAD

**Issue by davidrneves** [Comcast/scytale#18]
Hi, I'm trying to build scytale in a cento 7 server and I get this error:

/primaryHandler.go:78:72: fanoutOptions.NewDecoderPool undefined (type *wrphttp.FanoutOptions has no field or method NewDecoderPool)
./primaryHandler.go:79:55: fanoutOptions.NewEncoderPool undefined (type *wrphttp.FanoutOptions has no field or method NewEncoderPool)
./primaryHandler.go:91:72: fanoutOptions.NewDecoderPool undefined (type *wrphttp.FanoutOptions has no field or method NewDecoderPool)
./primaryHandler.go:92:55: fanoutOptions.NewEncoderPool undefined (type *wrphttp.FanoutOptions has no field or method NewEncoderPool)
./primaryHandler.go:176:43: not enough arguments in call to webhook.NewFactory
	have (*viper.Viper)
	want (*viper.Viper, *xmetrics.Registry)
./primaryHandler.go:195:27: not enough arguments in call to webHookFactory.Notifier.Initialize
	have (*mux.Router, *url.URL, "net/http".Handler, "github.com/go-kit/kit/log".Logger, nil)
	want (*mux.Router, *url.URL, "net/http".Handler, "github.com/go-kit/kit/log".Logger, *xmetrics.Registry, func() time.Time)

Whenever I run "go build" I obtained the mentioned error. Already checked that the needed packages are installed and updated. Could you please show me the correct build process?

Thanks!

**Comment by davidrneves** [comment]
I was able to install a docker image with centos 6 and run the scytale but now apparently I need AWS key to properly run the service.

How do I generate this key?

Thanks!

**Comment by schmidtw** [comment]
Yes, scytale needs to be connected to SNS to operate.  You need to sign up with AWS and get a key pair from them.

In the `aws` section of the configuration you'll put the accessKey, secretKey, region and topicArn.

`topic-name` for the topic name is arbitrary but needs to match.

```
{
	"fqdn": "scytale-prod-xxxx.example.com",

	"server": "scytale-prod-xxxx.example.com",
	"build": "0.1.1-67",
	"region": "pacific",
	"flavor": "unused",

	"primary": {
		"address": ":443",
		"certificateFile": "/etc/scytale/cert.pem",
		"keyFile": "/etc/scytale/key.pem"
	},

	"health": {
		"address": ":80",
		"logInterval": "60s"
	},

	"pprof": {
		"address": ":55555"
	},

	"metric": {
		"address": ":9391",
		"metricsOptions": {
			"namespace": "xmidt",
			"subsystem": "scytale"
		}
	},

	"fanout": {
		"method": "POST",
		"endpoints": [ "https://fabric.example.com:8080/api/v2/device/send" ],
		"authorization": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		"timeout": "127s",
		"clientTimeout": "30s",
		"maxClients": 1000,
		"concurrency": 100,
		"encoderPoolSize": 100,
		"decoderPoolSize": 100
	},


	"log" : {
		"file"      : "/var/log/scytale/scytaleLog.log",
		"level"     : "ERROR",
		"maxSize"   : 5242880,
		"maxBackup" : 3,
		"json"      : true
	},

	"jwtValidators": [
		{
			"keys": {
				"factory": {
					"uri": "https://jwt-issuer.example.com/keys/{keyId}"
				},
				"purpose": 0,
				"updateInterval": 604800000000000
			}
		}
	],
	
	"start": {
		"duration": 60000000000,
		"apiPath": "https://api.example.com/api/v2/hooks",
		"sat": {
			"path": "https://jwt-issuer.example.com/getJWT",
			"id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
			"secret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
			"capabilities": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
		}
	},

	"aws": {
		"accessKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		"secretKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		"env": "topic-name",
		"sns": {
			"region": "seattle",
			"topicArn": "arn:aws:sns:seattle:000000000000:topic-name",
			"urlPath" : "/api/v2/aws/sns"
		}
	}
}
```

**Comment by schmidtw** [comment]
Please re-open if still a problem.
