### ISSUE TITLE
curl to scytale URL returns 404 Not Found error

### ISSUE THREAD

**Issue by fchan2** [Comcast/scytale#7]
We have scytale, talaria, and tr1d1um running on a single machine with the three services currently listening:

> tcp        0      0 :::8096                     :::*                        LISTEN      4180/tr1d1um
tcp        0      0 :::8080                     :::*                        LISTEN      4157/talaria
tcp        0      0 :::6000                     :::*                        LISTEN      4136/scytale
tcp        0      0 :::8081                     :::*                        LISTEN      4157/talaria
tcp        0      0 :::6001                     :::*                        LISTEN      4136/scytale
tcp        0      0 :::6002                     :::*                        LISTEN      4136/scytale
tcp        0      0 :::8095                     :::*                        LISTEN      4180/tr1d1um

The RDK-B is currently connected to talaria on port 8080. If a curl command is executed, the following is displayed:

> [root@hummingbird talaria]# curl -i http://10.11.160.49:6000/api/v2/device/f8a097ea7206/stat
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Mon, 04 Dec 2017 17:18:18 GMT
Content-Length: 19
404 page not found

scytale.log file only shows the following:

`
{"configurationFile":"/etc/scytale/scytale.json","level":"info","ts":"2017-12-01T19:47:54.385961766Z"}
{"address":":6001","caller":"webpa.go:235","level":"info","msg":"starting server","name":"scytale.health","ts":"2017-12-01T19:47:54.386156863Z"}
{"caller":"health.go:118","level":"debug","msg":"Health Monitor Started","ts":"2017-12-01T19:47:54.386196615Z"}
{"address":":6002","caller":"webpa.go:244","level":"info","msg":"starting server","name":"scytale.pprof","ts":"2017-12-01T19:47:54.386209981Z"}
{"address":":6000","caller":"webpa.go:249","level":"info","msg":"starting server","name":"scytale","ts":"2017-12-01T19:47:54.386221128Z"}
`

Please see attachments for scytale.json and talaria.json configuration files.
[webpa config.zip](https://github.com/Comcast/scytale/files/1528118/webpa.config.zip)

**Comment by joe94** [comment]
@fchan2, @johnabass is currently working to add support for that feature. We will keep you posted.

**Comment by fchan2** [comment]
Hi @joe94, can you clarify which feature is not yet supported?

I was attempting to GET device parameters as documented in the link here:
[RDK-B WEBPA Commands](https://etwiki.sys.comcast.net/display/CPE/RDK-B+WEBPA+Commands)

...so I was under the impression that this should work?

**Comment by joe94** [comment]
The feature I am referring to is the ability to get the stats for a given device (specifically the `stat` endpoint is not yet supported in scytale). 

That said, you can get the device stats using talaria today using the following endpoint form:

`[your-talaria-machine]:[your-bind-address]/api/v2/device/mac:[your-device-mac-address]/stat`

**Comment by fchan2** [comment]
Cool, I can pull the `stat` now if I point it to talaria as you mentioned. 

Should GET TR-181 data models work if I point it to talaria as well? I gave it a try using this command and I got a "404 page not found" error.

`curl -i http://[my-talaria-machine]:[talaria bind address]/api/v2/device/mac:[device mac address]/config?names=Device.DeviceInfo.SerialNumber`

**Comment by joe94** [comment]
No, that won't work because that's outside talaria's concern. 

Few things:
- Last time I checked, the `stat` feature was more than 50% done.

- From my limited understanding of your business requirements (working TR-181 data models), most of your direct API hits should be to tr1d1um and not scytale or talaria. Remember you can also get the device stats using tr1d1um (once scytale supports it) using the same endpoint form as talaria!

**Comment by fchan2** [comment]
> From my limited understanding of your business requirements (working TR-181 data models), most of your direct API hits should be to tr1d1um and not scytale or talaria.

Can you elaborate on what this means from the context of server configuration? I believe the RDK-B device still needs to connect to the talaria websocket port in order to get to tr1d1um -- do I have that right?

**Comment by joe94** [comment]
Yes, absolutely. I just mean that for endpoints like `stat` and `config`, you would want to use tr1d1um directly (but  of course`tr1d1um` then in turns uses  `scytale` and `talaria`).

**Comment by fchan2** [comment]
Hmm...by using tr1d1um directly, do you mean using the `config` command above, but just replacing with the tr1d1um machine/ports? I just gave that a try and met with a 404 error again.

**Comment by fchan2** [comment]
Just to clarify, this is the command that I am using:
`curl -i http://[tr1d1um ip]:[tr1d1um port]/api/v2/device/mac:f8a097ea7206/config?names=Device.DeviceInfo.SerialNumber`

I did not modify any JSON files before running this since device stats using tr1d1um as an endpoint from scytale is not supported yet.

> HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Tue, 05 Dec 2017 17:36:41 GMT
Content-Length: 19
404 page not found

**Comment by johnabass** [comment]
Since you tried this via tr1d1um, this should be considered a tr1d1um issue externally.  You should not be invoking scytale directly.
